version: "2"

services:
  web:
    container_name: pvnauction_nginx
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    restart: always
